MUHU-179:added functionality to add new card if presale, insale og ev…
itk-dev/yesplan-asana pull request #14
Opened 2021-06-11 12:34 UTC by lilosti

…entdate is changed

2021-06-11 16:00 UTC, rimi-itk requested changes

2021-06-11 16:00 UTC, rimi-itk commented on src/Asana/AsanaEventManager.php
> +        */
Remove this code if not used.

2021-06-11 16:00 UTC, rimi-itk commented on src/Asana/AsanaEventManager.php
> +                $yesplanevent->setIsNewEvent(false);
Will lead to null dereference errors if the event is not found. Do you know for sure that it always exists?

2021-06-15 07:41 UTC, lilosti commented on src/Asana/AsanaEventManager.php
> +        */
not supposed be commented out...

2021-06-15 07:42 UTC, lilosti commented on src/Asana/AsanaEventManager.php
> +                $yesplanevent->setIsNewEvent(false);
You never know for sure..

2021-06-15 08:00 UTC, rimi-itk approved these changes

2021-06-15 08:01 UTC, merged