Feature/asana
itk-dev/yesplan-asana pull request #2
Opened 2020-06-10 11:05 UTC by lilosti

https://jira.itkdev.dk/browse/MUHU-153

2020-06-10 12:17 UTC, rimi-itk requested changes
Looks nice. Some cleanup is needed. Very good job for your first Symfony project.

2020-06-10 12:17 UTC, rimi-itk commented on src/Asana/AsanaApiClient.php
> +        $this->httpClient = HttpClient::create(['headers' => ['Authorization' => 'Bearer '.$bearer]]);
You should not instantiate the http client before it is needed. Move this to the `request` function.

2020-06-10 12:17 UTC, rimi-itk commented on src/Asana/AsanaApiClient.php
> +        return $this->httpClient->request($method, $path, $options);
Instantiate the http client here, e.g.

```php
if (null === $this->httpClient) {
  $this->httpClient = HttpClient::create(…);
}
```

2020-06-10 12:17 UTC, rimi-itk commented on src/Asana/AsanaApiClient.php
> +    //new events
Stray comment?

2020-06-10 12:17 UTC, rimi-itk commented on src/Asana/AsanaApiClient.php
> +        $boards = explode(',', $this->options['asana_new_event']);
Consider exploding the option in the resolveOptions.

2020-06-10 12:17 UTC, rimi-itk commented on src/Asana/AsanaApiClient.php
> +        $boards = explode(',', $this->options['asana_new_event_online']);
Consider exploding the option in the resolveOptions.

2020-06-10 12:17 UTC, rimi-itk commented on src/Asana/AsanaApiClient.php
> +        $title = 'Last Minute: '.$values['titel'];
This variable is not used.

2020-06-10 12:17 UTC, rimi-itk commented on src/Asana/AsanaApiClient.php
> +        $title = 'Få billetter: '.$values['titel'];
This variable is not used.

2020-06-10 12:17 UTC, rimi-itk commented on src/Asana/AsanaApiClient.php
> +    //Create the card in Asana
Stray comment.

2020-06-10 12:17 UTC, rimi-itk commented on src/Asana/AsanaApiClient.php
> +        // print_r($values['eventdate']->format('Y-m-d H:i:s'));
Leftover debug statement!

2020-06-10 12:17 UTC, rimi-itk commented on src/Asana/AsanaApiClient.php
> +        if (!empty($values['publicationdate'])) {
May be easier to read if written as
```
$publicationDate = !empty($values['publicationdate']) ? $values['publicationdate']->format(…) : '';
```

2020-06-10 12:17 UTC, rimi-itk commented on src/Asana/AsanaApiClient.php
> +            $eventDate = $values['eventdate']->format('Y-m-d H:i:s');
The date format is repeated here. Consider putting it in a class variable (I suppose the date format is the same for alle dates), e.g.

```
class AsanaApiClient {
  private const DATETIME_FORMAT = 'Y-m-d H:i:s';

  …
  $date->format(self::DATETIME_FORMAT);
  …
}
```

2020-06-10 12:17 UTC, rimi-itk commented on src/Asana/AsanaApiClient.php
> +            // print_r($options);
Leftover debug statement.

2020-06-10 12:17 UTC, rimi-itk commented on src/Asana/AsanaApiClient.php
> +            $this->logger->error('Card not created statuscode yesplan_id: '.$response->getStatusCode().' '.$response->getContent(false).' '.$values['id']);
Use the logger context (cf. https://github.com/php-fig/log/blob/master/Psr/Log/LoggerInterface.php) to store the response and use placeholders in the message, e.g.

```
$this->logger->error('Card not created {status_code}', ['status_code' => $response->getStatusCode(), 'response' => $response]);
```

2020-06-10 12:17 UTC, rimi-itk commented on src/Asana/AsanaApiClient.php
> +            $this->mailer->sendEmail('Error creating card', 'Error '.$response->getStatusCode().'URL: '.$url.'projectID: '.$projectId);
It is possible to have the logger mail the error message (so we don't have to do it manually here).

2020-06-10 12:17 UTC, rimi-itk commented on src/Asana/AsanaEventManager.php
> +            'eventdate' => $event->getEventDate(), //->format('Y-m-d H:i:s'),
Leftover comment.

2020-06-10 12:17 UTC, rimi-itk commented on src/Asana/AsanaEventManager.php
> +        $eventArray = [
Variable names should not end with `Array` – call it `$eventData`. Or skip the variable altogether and just return the value.

2020-06-10 12:17 UTC, rimi-itk commented on src/Asana/AsanaEventManager.php
> +            $this->cardCreated($lastMinuteEvent['id'], 'LastMinute');
Use constants for `'LastMinute'`, `'FewTickets'` etc.:

```
class … {
  private const LAST_MINUTE = 'LastMinute';
  …
}
```

This will make the code less prone to errors due to typos.

2020-06-10 12:17 UTC, rimi-itk commented on src/Asana/AsanaEventManager.php
> +            case 'LastMinute':
Use class const (`self::LAST_MINUTE`).

2020-06-10 12:17 UTC, rimi-itk commented on src/Command/AsanaPutCardsCommand.php
> +        $io = new SymfonyStyle($input, $output);
This variable is not used. If you want to write info to the console, pass a `Logger` to the `AsanaEventManager`, e.g. 

```
$logger = new ConsoleLogger($output);
$this->asanaEventManager->setLogger($logger);l
```

2020-06-10 12:17 UTC, rimi-itk commented on src/Command/YesplanDeleteOldEventsCommand.php
> +
Extra newline.

2020-06-10 12:17 UTC, rimi-itk commented on src/Command/YesplanDeleteOldEventsCommand.php
> +        $io = new SymfonyStyle($input, $output);
Unused variable.

2020-06-10 12:17 UTC, rimi-itk commented on src/Command/YesplanGetEventsCommand.php
> +
Extra newline.

2020-06-10 12:17 UTC, rimi-itk commented on src/Command/YesplanGetEventsCommand.php
> +        $io = new SymfonyStyle($input, $output);
Unused.

2020-06-10 12:17 UTC, rimi-itk commented on src/Controller/MailerController.php
> +class MailerController extends AbstractController
What's the purpose of this controller? Has it been used for testing? I think it should be removed.

2020-06-10 12:17 UTC, rimi-itk commented on src/Logging/Logger.php
> +class Logger
This class should be replaced with use of [LoggerTrait](https://github.com/php-fig/log/blob/master/Psr/Log/LoggerTrait.php).

2020-06-10 12:17 UTC, rimi-itk commented on src/Repository/YesplanEventRepository.php
> +class YesplanEventRepository extends ServiceEntityRepository
We have to talk about this class and the functions inside it. There may be better ways to handle this.

2020-06-10 12:17 UTC, rimi-itk commented on src/Repository/YesplanEventRepository.php
> +    //   return $qb->getQuery()->getResult();
Never commit code in comments. Remove it if it's not needed.

2020-06-10 12:17 UTC, rimi-itk commented on src/Yesplan/ApiClient.php
> +        $this->httpClient = HttpClient::create(['base_uri' => $this->options['url']]);
Move this to the `request` method.

2020-06-10 12:17 UTC, rimi-itk commented on src/Yesplan/ApiClient.php
> +            if (Response::HTTP_OK === $response->getStatusCode()) { //http statuskode ok
Leftover comment.

2020-06-10 12:17 UTC, rimi-itk commented on src/Yesplan/ApiClient.php
> +        $timeNow = new DateTime('NOW');
Passing `'NOW'` is not needed here. Just use `new DateTime()`.

2020-06-10 12:17 UTC, rimi-itk commented on src/Yesplan/ApiClient.php
> +        $time10Years = new DateTime('NOW');
Use `new DateTime('+10 years')` here.

2020-06-10 12:17 UTC, rimi-itk commented on src/Yesplan/ApiClient.php
> +        //$timeNow->format('Y-m-d H:i:s:')
Leftover comment.

2020-06-10 12:17 UTC, rimi-itk commented on src/Yesplan/ApiClient.php
> +        $url = 'api/events/event%3Adate%3A'.$dateString;
Use [`urlencode`](https://www.php.net/manual/en/function.urlencode.php) for this.

2020-06-10 12:17 UTC, rimi-itk commented on src/Yesplan/ApiClient.php
> +        $this->eventArray = [];
I don't see the usefulness of this variable.

2020-06-10 12:17 UTC, rimi-itk commented on src/Yesplan/ApiClient.php
> +                sleep(6);
This looks fishy …

2020-06-10 12:17 UTC, rimi-itk commented on src/Yesplan/ApiClient.php
> +                $id = '';
These lines can be removed.

2020-06-10 12:17 UTC, rimi-itk commented on src/Yesplan/ApiClient.php
> +                $responseArray = $response->toArray();
Call it `result` or similar (just not something ending with `Array`).

2020-06-10 12:17 UTC, rimi-itk commented on src/Yesplan/ApiClient.php
> +                foreach ($responseArray['data'] as $data) {
Should be rewritten to something along the lines of

```
$events = [];
foreach ($result['data'] as $item) {
  $event = [
    'id' => $item['id'],
    'data' => $item,
    'title' => $item['name'],
    …
  ];

  if (!empty($data['locations']['next'])) {
    $event['location'] = …;
  }

  $events[$item['id']] = $event;
}

return $events;
```

2020-06-10 12:17 UTC, rimi-itk commented on src/Yesplan/ApiClient.php
> +    private function getCustomData(string $id): void
This function should build and return a value (it's called `getCustomData`) and not use `$this->eventArray`.

2020-06-10 12:17 UTC, rimi-itk commented on src/Yesplan/ApiClient.php
> +            sleep(6);
We have to find a better way to handle this.

2020-06-10 12:17 UTC, rimi-itk commented on src/Yesplan/EventManager.php
> +            $event->setMarketingBudget($data['marketing_budget']);
Use chaining here:

```
$event
  ->setData(…)
  ->setTitle(…)
  ->set…
```

2020-06-10 12:17 UTC, rimi-itk commented on src/Yesplan/EventManager.php
> +            $event->setTicketCapacity((int) ($data['capacity']));
You don't have to wrap `$data[…]` in `()`, just write `(int) $data[…]`.

2020-06-10 12:17 UTC, rimi-itk commented on src/Yesplan/EventManager.php
> +            $calculateCapacityPercentage = 0;
Should no be called `calculateCapacityPercentage`, but just `capacityPercentage` (since it's what it is).

2020-06-10 12:17 UTC, rimi-itk commented on src/Yesplan/EventManager.php
> +                //dont add date if conversion fails - should be logged
Create a helper function for getting the date (this will also help with logging errors):

```
$publicationDate = $this->getDateTime($data['publication_date']);
```

2020-06-10 12:17 UTC, rimi-itk commented on src/Yesplan/EventManager.php
> +                //  echo 'trnsaformed' . $eventDate . '.' .  $data['eventDate'];
Remove this.

2020-06-10 12:17 UTC, rimi-itk commented on src/Yesplan/EventManager.php
> +            // $event->setEventDate(DateTime::createFromFormat('Y-m-d\TH:i',$data['eventDate']));
Leftover comment.

2020-06-10 12:17 UTC, rimi-itk commented on src/Yesplan/EventManager.php
> +            //  print_r($event->getId());
Remove this.

2020-06-17 05:52 UTC, lilosti commented on src/Logging/Logger.php
> +class Logger
Why?

2020-06-17 06:47 UTC, lilosti commented on src/Yesplan/ApiClient.php
> +                foreach ($responseArray['data'] as $data) {
how about the customdata?

2020-06-23 10:20 UTC, rimi-itk approved these changes

2020-06-23 10:23 UTC, merged